name: Master CI Check Warnings

on:
  push:
    branches:
      - master

jobs:
  check_warnings:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.7]

    name: Check for warnings
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/vircadia/video.git
        pip install -U Sphinx==3.5.4
        pip install --upgrade myst-parser
        pip install sphinx_rtd_theme
        pip install 'jinja2<3.1'
        pip install 'myst-parser==0.16.0'
        pip install  attr
        pip install attrs
    - name: Check source documentation
      shell: bash
      run: |
        cd docs
        make SPHINXOPTS="-W --keep-going" html
    - name: Check German documentation
      if: ${{ success() || failure() }}
      shell: bash
      run: |
        cd docs
        make BUILDDIR=build-de SPHINXOPTS="-Dlanguage=de -W --keep-going" html
    - name: Check French documentation
      if: ${{ success() || failure() }}
      shell: bash
      run: |
        cd docs
        make BUILDDIR=build-fr SPHINXOPTS="-Dlanguage=fr -W --keep-going" html
    - name: Check Japanese documentation
      if: ${{ success() || failure() }}
      shell: bash
      run: |
        cd docs
        make BUILDDIR=build-jp SPHINXOPTS="-Dlanguage=jp -W --keep-going" html
    - name: Check Spanish documentation
      if: ${{ success() || failure() }}
      shell: bash
      run: |
        cd docs
        make BUILDDIR=build-es SPHINXOPTS="-Dlanguage=es -W --keep-going" html
    - name: Check Korean documentation
      if: ${{ success() || failure() }}
      shell: bash
      run: |
        cd docs
        make BUILDDIR=build-ko SPHINXOPTS="-Dlanguage=ko -W --keep-going" html
    - name: Check Simplified Chinese documentation
      if: ${{ success() || failure() }}
      shell: bash
      run: |
        cd docs
        make BUILDDIR=build-zh_CN SPHINXOPTS="-Dlanguage=zh_CN -W --keep-going" html
    - name: Check Catalan documentation
      if: ${{ success() || failure() }}
      shell: bash
      run: |
        cd docs
        make BUILDDIR=build-ca SPHINXOPTS="-Dlanguage=ca -W --keep-going" html
